apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
spec:
  rules:
    - http:
        paths:
          - path: /admitad-service
            pathType: Prefix
            backend:
              service:
                name: admitad-service
                port:
                  number: 80
    - http:
         paths:
          - path: /spring-admin
            pathType: Prefix
            backend:
              service:
                name: spring-admin
                port:
                  number: 80